name: Deploy on pull request

on:
  pull_request_review:
    type: [submitted]
env:
  FILE_NAME: hello-server

jobs:  
  check-state:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        id-token: write

    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'master'                                                                                                       
    steps:
      - run: |
         echo ${{ github.event.review.state }}
         echo ${{ github.event.pull_request.base.ref }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: is_inference_dir_change
        uses: dorny/paths-filter@v2.2.1
        id: inferene_dir_changes
        with:
          filters: |
            inference:
              - 'inference/*.*' 
    
      - name: Build ${{ env.FILE_NAME }} for ubuntu-latest
        if: ${{ steps.inference_dir_change.outputs.inference == 'true' }}
        run: |
          echo $HOME
          echo $GITHUB_WORKSPACE
          ./build_push.sh
        working-directory: 
          ./