name: Deploy on pull request

on:
  pull_request_review:
    type: [submitted]
env:
  FILE_NAME: hello-server

jobs:
  check-inference-dir-change:
    name: check-src-simple-inferenceService-dir-changed
    runs-on: ubuntu-latest
    permissions:
        packages: write
        contents: read
        id-token: write
    steps:
      - uses: actions/checkout
        with:
          fetch-depth: 0
      - id: did-inference-change
        run: echo "::set-output name=value::$(git diff --quiet HEAD origin/master  -- inference/ || echo true)"
    outputs:
     check-inference-dir-output: ${{ steps.did-inference-change.outputs.value }}

  check-state:
    runs-on: ubuntu-latest
    needs: check-inference-dir-change
    #if: needs.check-inference-dir-change.check-inference-dir-output == 'true' && github.event.review.state == 'approved'
    steps:
      - run: |
         echo ${{ needs.check-inference-dir-change.check-inference-dir-output }}
      - name: Check out code
        uses: actions/checkout@v3
    
      - name: Build ${{ env.FILE_NAME }} for ubuntu-latest
        run: |
          echo $HOME
          echo $GITHUB_WORKSPACE
          ./build_push.sh
        working-directory: 
          ./